packages:
  - name: cron
    environment:
      APP_URL: "https://silly-debates-6vhp9.ondigitalocean.app"
      CRON_SECRET: "${CRON_SECRET}"
    functions:
      - name: close-debate
        runtime: nodejs:18
        triggers:
          - name: close-debate-schedule
            sourceType: scheduler
            sourceDetails:
              cron: "59 13 * * *"
      - name: new-debate
        runtime: nodejs:18
        triggers:
          - name: new-debate-schedule
            sourceType: scheduler
            sourceDetails:
              cron: "1 14 * * *"
